"""Extended taxonomy seed — Azerbaijan market + global coverage.

Combined with SEED_ENTRIES in training/taxonomy.py by
scripts/discover_vehicle_taxonomy.py. Format: (make, model, body_type).
"""
EXTRA_ENTRIES: list[tuple[str, str, str]] = [
    # --- Lada / VAZ ---
    ("Lada", "Granta", "Sedan"), ("Lada", "Vesta", "Sedan"),
    ("Lada", "Niva", "SUV"), ("Lada", "Priora", "Sedan"),
    ("Lada", "Kalina", "Hatchback"), ("Lada", "Largus", "Wagon"),
    ("Lada", "XRAY", "Crossover"), ("Lada", "2114", "Hatchback"),
    ("Lada", "2110", "Sedan"), ("Lada", "2107", "Sedan"),
    # --- GAZ / UAZ ---
    ("GAZ", "Volga", "Sedan"), ("GAZ", "Gazelle", "Van"), ("GAZ", "Sobol", "Van"),
    ("UAZ", "Patriot", "SUV"), ("UAZ", "Hunter", "SUV"), ("UAZ", "Bukhanka", "Van"),
    # --- Volkswagen (the missing brand from the bug report) ---
    ("Volkswagen", "Polo", "Sedan"), ("Volkswagen", "Golf", "Hatchback"),
    ("Volkswagen", "Jetta", "Sedan"), ("Volkswagen", "Passat", "Sedan"),
    ("Volkswagen", "Tiguan", "SUV"), ("Volkswagen", "Touareg", "SUV"),
    ("Volkswagen", "T-Roc", "SUV"), ("Volkswagen", "Arteon", "Sedan"),
    ("Volkswagen", "Teramont", "SUV"), ("Volkswagen", "Caddy", "Van"),
    ("Volkswagen", "Transporter", "Van"), ("Volkswagen", "Amarok", "Pickup"),
    # --- Audi / Skoda / Opel ---
    ("Audi", "A3", "Sedan"), ("Audi", "A4", "Sedan"), ("Audi", "A5", "Coupe"),
    ("Audi", "A6", "Sedan"), ("Audi", "A7", "Sedan"), ("Audi", "A8", "Sedan"),
    ("Audi", "Q3", "SUV"), ("Audi", "Q5", "SUV"), ("Audi", "Q7", "SUV"), ("Audi", "Q8", "SUV"),
    ("Skoda", "Octavia", "Sedan"), ("Skoda", "Superb", "Sedan"),
    ("Skoda", "Fabia", "Hatchback"), ("Skoda", "Rapid", "Sedan"),
    ("Skoda", "Kodiaq", "SUV"), ("Skoda", "Karoq", "SUV"),
    ("Opel", "Astra", "Sedan"), ("Opel", "Corsa", "Hatchback"),
    ("Opel", "Insignia", "Sedan"), ("Opel", "Mokka", "SUV"),
    ("Opel", "Vectra", "Sedan"), ("Opel", "Zafira", "MPV"),
    # --- Hyundai / Kia ---
    ("Hyundai", "Accent", "Sedan"), ("Hyundai", "Elantra", "Sedan"),
    ("Hyundai", "Sonata", "Sedan"), ("Hyundai", "Tucson", "SUV"),
    ("Hyundai", "Santa Fe", "SUV"), ("Hyundai", "Creta", "SUV"),
    ("Hyundai", "i30", "Hatchback"), ("Hyundai", "Solaris", "Sedan"),
    ("Kia", "Rio", "Sedan"), ("Kia", "Cerato", "Sedan"), ("Kia", "K5", "Sedan"),
    ("Kia", "Sportage", "SUV"), ("Kia", "Sorento", "SUV"), ("Kia", "Soul", "Crossover"),
    ("Kia", "Ceed", "Hatchback"), ("Kia", "Seltos", "SUV"), ("Kia", "Carnival", "MPV"),
    # --- Toyota / Lexus ---
    ("Toyota", "Yaris", "Hatchback"), ("Toyota", "C-HR", "SUV"),
    ("Toyota", "Highlander", "SUV"), ("Toyota", "Prado", "SUV"),
    ("Toyota", "Fortuner", "SUV"), ("Toyota", "Avalon", "Sedan"),
    ("Lexus", "ES", "Sedan"), ("Lexus", "IS", "Sedan"), ("Lexus", "LS", "Sedan"),
    ("Lexus", "LX", "SUV"), ("Lexus", "NX", "SUV"), ("Lexus", "RX", "SUV"), ("Lexus", "GX", "SUV"),
    # --- Mercedes-Benz / BMW extensions ---
    ("Mercedes-Benz", "A-Class", "Hatchback"), ("Mercedes-Benz", "GLA", "SUV"),
    ("Mercedes-Benz", "GLE", "SUV"), ("Mercedes-Benz", "GLS", "SUV"),
    ("Mercedes-Benz", "G-Class", "SUV"), ("Mercedes-Benz", "CLA", "Sedan"),
    ("Mercedes-Benz", "Vito", "Van"),
    ("BMW", "1 Series", "Hatchback"), ("BMW", "2 Series", "Coupe"),
    ("BMW", "4 Series", "Coupe"), ("BMW", "6 Series", "Coupe"),
    ("BMW", "7 Series", "Sedan"), ("BMW", "X1", "SUV"), ("BMW", "X4", "SUV"),
    ("BMW", "X6", "SUV"), ("BMW", "X7", "SUV"),
    # --- Nissan / Mazda / Honda / Mitsubishi / Subaru / Suzuki ---
    ("Nissan", "Almera", "Sedan"), ("Nissan", "Qashqai", "SUV"),
    ("Nissan", "X-Trail", "SUV"), ("Nissan", "Juke", "SUV"),
    ("Nissan", "Murano", "SUV"), ("Nissan", "Patrol", "SUV"),
    ("Nissan", "Teana", "Sedan"), ("Nissan", "Tiida", "Hatchback"),
    ("Nissan", "Navara", "Pickup"), ("Nissan", "Leaf", "Hatchback"), ("Nissan", "Micra", "Hatchback"),
    ("Mazda", "Mazda3", "Sedan"), ("Mazda", "Mazda6", "Sedan"),
    ("Mazda", "CX-5", "SUV"), ("Mazda", "CX-9", "SUV"), ("Mazda", "CX-30", "SUV"),
    ("Honda", "Civic", "Sedan"), ("Honda", "Accord", "Sedan"),
    ("Honda", "CR-V", "SUV"), ("Honda", "HR-V", "SUV"), ("Honda", "Pilot", "SUV"),
    ("Mitsubishi", "Lancer", "Sedan"), ("Mitsubishi", "Outlander", "SUV"),
    ("Mitsubishi", "Pajero", "SUV"), ("Mitsubishi", "ASX", "SUV"),
    ("Mitsubishi", "Pajero Sport", "SUV"), ("Mitsubishi", "L200", "Pickup"),
    ("Subaru", "Forester", "SUV"), ("Subaru", "Outback", "Wagon"),
    ("Subaru", "Impreza", "Sedan"), ("Subaru", "XV", "SUV"),
    ("Suzuki", "Swift", "Hatchback"), ("Suzuki", "Vitara", "SUV"),
    ("Suzuki", "Jimny", "SUV"), ("Suzuki", "SX4", "SUV"),
    # --- Ford / Chevrolet / Ravon / Daewoo ---
    ("Ford", "Focus", "Sedan"), ("Ford", "Fiesta", "Hatchback"),
    ("Ford", "Mondeo", "Sedan"), ("Ford", "Kuga", "SUV"),
    ("Ford", "Explorer", "SUV"), ("Ford", "Transit", "Van"),
    ("Ford", "Ranger", "Pickup"), ("Ford", "Mustang", "Coupe"), ("Ford", "Fusion", "Sedan"),
    ("Chevrolet", "Cruze", "Sedan"), ("Chevrolet", "Lacetti", "Sedan"),
    ("Chevrolet", "Cobalt", "Sedan"), ("Chevrolet", "Nexia", "Sedan"),
    ("Chevrolet", "Spark", "Hatchback"), ("Chevrolet", "Malibu", "Sedan"),
    ("Chevrolet", "Captiva", "SUV"), ("Chevrolet", "Tahoe", "SUV"),
    ("Chevrolet", "Aveo", "Sedan"), ("Chevrolet", "Equinox", "SUV"),
    ("Ravon", "Nexia R3", "Sedan"), ("Ravon", "R4", "Sedan"), ("Ravon", "Gentra", "Sedan"),
    ("Daewoo", "Nexia", "Sedan"), ("Daewoo", "Matiz", "Hatchback"), ("Daewoo", "Gentra", "Sedan"),
    # --- Renault / Peugeot / Citroen / Fiat / Dacia ---
    ("Renault", "Logan", "Sedan"), ("Renault", "Duster", "SUV"),
    ("Renault", "Sandero", "Hatchback"), ("Renault", "Megane", "Sedan"),
    ("Renault", "Fluence", "Sedan"), ("Renault", "Kaptur", "SUV"), ("Renault", "Arkana", "SUV"),
    ("Peugeot", "206", "Hatchback"), ("Peugeot", "301", "Sedan"),
    ("Peugeot", "308", "Hatchback"), ("Peugeot", "408", "Sedan"),
    ("Peugeot", "508", "Sedan"), ("Peugeot", "2008", "SUV"),
    ("Peugeot", "3008", "SUV"), ("Peugeot", "5008", "SUV"),
    ("Peugeot", "Partner", "Van"), ("Peugeot", "Boxer", "Van"),
    ("Citroen", "C3", "Hatchback"), ("Citroen", "C4", "Sedan"),
    ("Citroen", "C-Elysee", "Sedan"), ("Citroen", "Berlingo", "Van"),
    ("Fiat", "Doblo", "Van"), ("Fiat", "Egea", "Sedan"), ("Fiat", "500", "Hatchback"),
    ("Dacia", "Logan", "Sedan"), ("Dacia", "Duster", "SUV"), ("Dacia", "Sandero", "Hatchback"),
    # --- Chinese brands ---
    ("Chery", "Tiggo 4", "SUV"), ("Chery", "Tiggo 7", "SUV"), ("Chery", "Tiggo 8", "SUV"),
    ("Chery", "Arrizo 5", "Sedan"), ("Chery", "Bonus", "Sedan"),
    ("Haval", "H6", "SUV"), ("Haval", "Jolion", "SUV"), ("Haval", "F7", "SUV"),
    ("Geely", "Atlas", "SUV"), ("Geely", "Coolray", "SUV"), ("Geely", "Emgrand", "Sedan"),
    ("Lifan", "X60", "SUV"), ("Lifan", "Solano", "Sedan"), ("Lifan", "X50", "SUV"),
    # --- Premium / other ---
    ("Land Rover", "Defender", "SUV"), ("Land Rover", "Discovery", "SUV"),
    ("Land Rover", "Range Rover", "SUV"), ("Land Rover", "Range Rover Sport", "SUV"),
    ("Land Rover", "Range Rover Evoque", "SUV"), ("Land Rover", "Freelander", "SUV"),
    ("Porsche", "Cayenne", "SUV"), ("Porsche", "Macan", "SUV"),
    ("Porsche", "Panamera", "Sedan"), ("Porsche", "911", "Coupe"),
    ("Volvo", "S60", "Sedan"), ("Volvo", "S90", "Sedan"),
    ("Volvo", "XC40", "SUV"), ("Volvo", "XC60", "SUV"), ("Volvo", "XC90", "SUV"),
    ("Infiniti", "Q50", "Sedan"), ("Infiniti", "QX50", "SUV"),
    ("Infiniti", "QX60", "SUV"), ("Infiniti", "QX80", "SUV"), ("Infiniti", "FX", "SUV"),
    ("Jeep", "Grand Cherokee", "SUV"), ("Jeep", "Cherokee", "SUV"),
    ("Jeep", "Wrangler", "SUV"), ("Jeep", "Compass", "SUV"),
    ("Tesla", "Model 3", "Sedan"), ("Tesla", "Model Y", "SUV"),
    ("Tesla", "Model S", "Sedan"), ("Tesla", "Model X", "SUV"),
    # --- Iranian brands (common in region) ---
    ("Iran Khodro", "Samand", "Sedan"), ("Iran Khodro", "Dena", "Sedan"),
    ("Iran Khodro", "Runna", "Sedan"), ("Iran Khodro", "Peugeot 405", "Sedan"),
    ("Saipa", "Tiba", "Sedan"), ("Saipa", "Quick", "Hatchback"), ("Saipa", "Pride", "Sedan"),
    # --- ZAZ ---
    ("ZAZ", "Chance", "Sedan"), ("ZAZ", "Slavuta", "Hatchback"), ("ZAZ", "Tavria", "Hatchback"),
    # --- Changan ---
    ("Changan", "Alsvin", "Sedan"), ("Changan", "Eado", "Sedan"),
    ("Changan", "Benben", "Hatchback"), ("Changan", "Lumin", "Hatchback"),
    ("Changan", "CS15", "SUV"), ("Changan", "CS35", "SUV"), ("Changan", "CS55", "SUV"),
    ("Changan", "CS75", "SUV"), ("Changan", "CS85", "SUV"), ("Changan", "CS95", "SUV"),
    ("Changan", "UNI-T", "SUV"), ("Changan", "UNI-K", "SUV"), ("Changan", "UNI-V", "Sedan"),
    ("Changan", "Hunter", "Pickup"),
    ("Changan", "UNI-Z", "SUV"), ("Changan", "Nevo A05", "Sedan"),
    ("Changan", "Oshan X5", "SUV"), ("Changan", "Qiyuan Q05", "SUV"),
    ("Changan", "Alsvin V7", "Sedan"),
    # --- Seres / GAC (discovered from turbo.az) ---
    ("Seres", "M5", "SUV"), ("Seres", "M7", "SUV"), ("Seres", "M9", "SUV"),
    ("GAC", "GS3", "SUV"), ("GAC", "GS4", "SUV"), ("GAC", "GS8", "SUV"),
    ("GAC", "Empow", "Sedan"), ("GAC", "Emkoo", "SUV"),
    # --- BYD ---
    ("BYD", "Song", "SUV"), ("BYD", "Tang", "SUV"), ("BYD", "Han", "Sedan"),
    ("BYD", "Qin", "Sedan"), ("BYD", "Atto 3", "SUV"), ("BYD", "Dolphin", "Hatchback"),
    ("BYD", "Seagull", "Hatchback"), ("BYD", "Yuan", "SUV"),
    # --- MG ---
    ("MG", "MG3", "Hatchback"), ("MG", "MG5", "Sedan"), ("MG", "MG6", "Sedan"),
    ("MG", "ZS", "SUV"), ("MG", "HS", "SUV"), ("MG", "RX5", "SUV"), ("MG", "Gloster", "SUV"),
    # --- JAC / Jetour / Exeed / Omoda / DFSK ---
    ("JAC", "J7", "Sedan"), ("JAC", "JS4", "SUV"), ("JAC", "S3", "SUV"),
    ("JAC", "S5", "SUV"), ("JAC", "T8", "Pickup"),
    ("Jetour", "X70", "SUV"), ("Jetour", "X90", "SUV"),
    ("Jetour", "Dashing", "SUV"), ("Jetour", "T2", "SUV"),
    ("Exeed", "LX", "SUV"), ("Exeed", "TXL", "SUV"), ("Exeed", "VX", "SUV"),
    ("Omoda", "C5", "SUV"), ("Omoda", "S5", "Sedan"),
    ("DFSK", "Glory 580", "SUV"),
    # --- Dongfeng / FAW / Hongqi / BAIC ---
    ("Dongfeng", "AX7", "SUV"), ("Dongfeng", "Aeolus", "Sedan"),
    ("FAW", "B70", "Sedan"), ("FAW", "T99", "SUV"), ("FAW", "X40", "SUV"),
    ("Hongqi", "H5", "Sedan"), ("Hongqi", "H9", "Sedan"), ("Hongqi", "HS5", "SUV"),
    ("BAIC", "X35", "SUV"), ("BAIC", "X55", "SUV"), ("BAIC", "BJ40", "SUV"),
    # --- Zeekr / Li Auto / NIO / XPeng / Wuling ---
    ("Zeekr", "001", "Wagon"), ("Zeekr", "X", "SUV"), ("Zeekr", "009", "MPV"),
    ("Li Auto", "L7", "SUV"), ("Li Auto", "L8", "SUV"), ("Li Auto", "L9", "SUV"),
    ("NIO", "ES6", "SUV"), ("NIO", "ES8", "SUV"), ("NIO", "ET5", "Sedan"), ("NIO", "ET7", "Sedan"),
    ("XPeng", "P7", "Sedan"), ("XPeng", "G6", "SUV"), ("XPeng", "G9", "SUV"),
    ("Wuling", "Hongguang", "MPV"), ("Wuling", "Mini", "Hatchback"),
    # --- Chery / Geely / Haval expansion ---
    ("Chery", "Tiggo 2", "SUV"), ("Chery", "Tiggo 3", "SUV"), ("Chery", "Tiggo 9", "SUV"),
    ("Geely", "Tugella", "SUV"), ("Geely", "Monjaro", "SUV"), ("Geely", "Preface", "Sedan"),
    ("Haval", "H2", "SUV"), ("Haval", "H9", "SUV"), ("Haval", "Dargo", "SUV"),
    # --- Moskvich (revived, common in region) ---
    ("Moskvich", "3", "SUV"), ("Moskvich", "6", "Sedan"),
    # --- other gaps ---
    ("Lada", "Niva Travel", "SUV"),
    ("BMW", "iX", "SUV"),
    ("Chevrolet", "Onix", "Sedan"), ("Chevrolet", "Tracker", "SUV"),
    ("Toyota", "Corolla Cross", "SUV"),
    # --- heavy trucks (radar-relevant) ---
    ("HOWO", "T7H", "HeavyTruck"), ("HOWO", "T5G", "HeavyTruck"), ("HOWO", "A7", "HeavyTruck"),
    ("SITRAK", "C7H", "HeavyTruck"),
    # --- Haval expansion ---
    ("Haval", "Raptor", "SUV"),
    # --- newly discovered on turbo.az ---
    ("Jaecoo", "J7", "SUV"), ("Jaecoo", "J8", "SUV"),
    ("Voyah", "Free", "SUV"), ("Voyah", "Dreamer", "MPV"),
    ("Rox", "01", "SUV"),
    ("Seat", "Leon", "Hatchback"), ("Seat", "Ibiza", "Hatchback"), ("Seat", "Ateca", "SUV"),
    ("Mini", "Cooper", "Hatchback"), ("Mini", "Countryman", "SUV"),
    ("GMC", "Yukon", "SUV"),
    ("Cadillac", "Escalade", "SUV"), ("Cadillac", "XT5", "SUV"),
    ("Maserati", "Ghibli", "Sedan"), ("Maserati", "Levante", "SUV"), ("Maserati", "Grecale", "SUV"),
    ("Ferrari", "Roma", "Coupe"), ("Ferrari", "296", "Coupe"),
    ("Bentley", "Bentayga", "SUV"), ("Bentley", "Continental", "Coupe"),
    ("MAN", "TGS", "HeavyTruck"), ("MAN", "TGX", "HeavyTruck"),
    ("KamAZ", "5490", "HeavyTruck"), ("KamAZ", "6520", "HeavyTruck"),
    ("Shacman", "X3000", "HeavyTruck"),
    ("Radar", "RD6", "Pickup"),
    ("Mercedes-Benz", "Maybach S-Class", "Sedan"),
]
