"""Extended taxonomy seed — Azerbaijan market + global coverage.

Combined with SEED_ENTRIES in training/taxonomy.py by
scripts/discover_vehicle_taxonomy.py. Format: (make, model, body_type).
"""
EXTRA_ENTRIES: list[tuple[str, str, str]] = [
    # --- Lada / VAZ ---
    ("Lada", "Granta", "Sedan"), ("Lada", "Vesta", "Sedan"),
    ("Lada", "Niva", "SUV"), ("Lada", "Priora", "Sedan"),
    ("Lada", "Kalina", "Hatchback"), ("Lada", "Largus", "Wagon"),
    ("Lada", "XRAY", "Crossover"), ("Lada", "2114", "Hatchback"),
    ("Lada", "2110", "Sedan"), ("Lada", "2107", "Sedan"),
    # --- GAZ / UAZ ---
    ("GAZ", "Volga", "Sedan"), ("GAZ", "Gazelle", "Van"), ("GAZ", "Sobol", "Van"),
    ("UAZ", "Patriot", "SUV"), ("UAZ", "Hunter", "SUV"), ("UAZ", "Bukhanka", "Van"),
    # --- Volkswagen (the missing brand from the bug report) ---
    ("Volkswagen", "Polo", "Sedan"), ("Volkswagen", "Golf", "Hatchback"),
    ("Volkswagen", "Jetta", "Sedan"), ("Volkswagen", "Passat", "Sedan"),
    ("Volkswagen", "Tiguan", "SUV"), ("Volkswagen", "Touareg", "SUV"),
    ("Volkswagen", "T-Roc", "SUV"), ("Volkswagen", "Arteon", "Sedan"),
    ("Volkswagen", "Teramont", "SUV"), ("Volkswagen", "Caddy", "Van"),
    ("Volkswagen", "Transporter", "Van"), ("Volkswagen", "Amarok", "Pickup"),
    # --- Audi / Skoda / Opel ---
    ("Audi", "A3", "Sedan"), ("Audi", "A4", "Sedan"), ("Audi", "A5", "Coupe"),
    ("Audi", "A6", "Sedan"), ("Audi", "A7", "Sedan"), ("Audi", "A8", "Sedan"),
    ("Audi", "Q3", "SUV"), ("Audi", "Q5", "SUV"), ("Audi", "Q7", "SUV"), ("Audi", "Q8", "SUV"),
    ("Skoda", "Octavia", "Sedan"), ("Skoda", "Superb", "Sedan"),
    ("Skoda", "Fabia", "Hatchback"), ("Skoda", "Rapid", "Sedan"),
    ("Skoda", "Kodiaq", "SUV"), ("Skoda", "Karoq", "SUV"),
    ("Opel", "Astra", "Sedan"), ("Opel", "Corsa", "Hatchback"),
    ("Opel", "Insignia", "Sedan"), ("Opel", "Mokka", "SUV"),
    ("Opel", "Vectra", "Sedan"), ("Opel", "Zafira", "MPV"),
    # --- Hyundai / Kia ---
    ("Hyundai", "Accent", "Sedan"), ("Hyundai", "Elantra", "Sedan"),
    ("Hyundai", "Sonata", "Sedan"), ("Hyundai", "Tucson", "SUV"),
    ("Hyundai", "Santa Fe", "SUV"), ("Hyundai", "Creta", "SUV"),
    ("Hyundai", "i30", "Hatchback"), ("Hyundai", "Solaris", "Sedan"),
    ("Kia", "Rio", "Sedan"), ("Kia", "Cerato", "Sedan"), ("Kia", "K5", "Sedan"),
    ("Kia", "Sportage", "SUV"), ("Kia", "Sorento", "SUV"), ("Kia", "Soul", "Crossover"),
    ("Kia", "Ceed", "Hatchback"), ("Kia", "Seltos", "SUV"), ("Kia", "Carnival", "MPV"),
    # --- Toyota / Lexus ---
    ("Toyota", "Yaris", "Hatchback"), ("Toyota", "C-HR", "SUV"),
    ("Toyota", "Highlander", "SUV"), ("Toyota", "Prado", "SUV"),
    ("Toyota", "Fortuner", "SUV"), ("Toyota", "Avalon", "Sedan"),
    ("Lexus", "ES", "Sedan"), ("Lexus", "IS", "Sedan"), ("Lexus", "LS", "Sedan"),
    ("Lexus", "LX", "SUV"), ("Lexus", "NX", "SUV"), ("Lexus", "RX", "SUV"), ("Lexus", "GX", "SUV"),
    # --- Mercedes-Benz / BMW extensions ---
    ("Mercedes-Benz", "A-Class", "Hatchback"), ("Mercedes-Benz", "GLA", "SUV"),
    ("Mercedes-Benz", "GLE", "SUV"), ("Mercedes-Benz", "GLS", "SUV"),
    ("Mercedes-Benz", "G-Class", "SUV"), ("Mercedes-Benz", "CLA", "Sedan"),
    ("Mercedes-Benz", "Vito", "Van"),
    ("BMW", "1 Series", "Hatchback"), ("BMW", "2 Series", "Coupe"),
    ("BMW", "4 Series", "Coupe"), ("BMW", "6 Series", "Coupe"),
    ("BMW", "7 Series", "Sedan"), ("BMW", "X1", "SUV"), ("BMW", "X4", "SUV"),
    ("BMW", "X6", "SUV"), ("BMW", "X7", "SUV"),
    # --- Nissan / Mazda / Honda / Mitsubishi / Subaru / Suzuki ---
    ("Nissan", "Almera", "Sedan"), ("Nissan", "Qashqai", "SUV"),
    ("Nissan", "X-Trail", "SUV"), ("Nissan", "Juke", "SUV"),
    ("Nissan", "Murano", "SUV"), ("Nissan", "Patrol", "SUV"),
    ("Nissan", "Teana", "Sedan"), ("Nissan", "Tiida", "Hatchback"),
    ("Nissan", "Navara", "Pickup"), ("Nissan", "Leaf", "Hatchback"), ("Nissan", "Micra", "Hatchback"),
    ("Mazda", "Mazda3", "Sedan"), ("Mazda", "Mazda6", "Sedan"),
    ("Mazda", "CX-5", "SUV"), ("Mazda", "CX-9", "SUV"), ("Mazda", "CX-30", "SUV"),
    ("Honda", "Civic", "Sedan"), ("Honda", "Accord", "Sedan"),
    ("Honda", "CR-V", "SUV"), ("Honda", "HR-V", "SUV"), ("Honda", "Pilot", "SUV"),
    ("Mitsubishi", "Lancer", "Sedan"), ("Mitsubishi", "Outlander", "SUV"),
    ("Mitsubishi", "Pajero", "SUV"), ("Mitsubishi", "ASX", "SUV"),
    ("Mitsubishi", "Pajero Sport", "SUV"), ("Mitsubishi", "L200", "Pickup"),
    ("Subaru", "Forester", "SUV"), ("Subaru", "Outback", "Wagon"),
    ("Subaru", "Impreza", "Sedan"), ("Subaru", "XV", "SUV"),
    ("Suzuki", "Swift", "Hatchback"), ("Suzuki", "Vitara", "SUV"),
    ("Suzuki", "Jimny", "SUV"), ("Suzuki", "SX4", "SUV"),
    # --- Ford / Chevrolet / Ravon / Daewoo ---
    ("Ford", "Focus", "Sedan"), ("Ford", "Fiesta", "Hatchback"),
    ("Ford", "Mondeo", "Sedan"), ("Ford", "Kuga", "SUV"),
    ("Ford", "Explorer", "SUV"), ("Ford", "Transit", "Van"),
    ("Ford", "Ranger", "Pickup"), ("Ford", "Mustang", "Coupe"), ("Ford", "Fusion", "Sedan"),
    ("Chevrolet", "Cruze", "Sedan"), ("Chevrolet", "Lacetti", "Sedan"),
    ("Chevrolet", "Cobalt", "Sedan"), ("Chevrolet", "Nexia", "Sedan"),
    ("Chevrolet", "Spark", "Hatchback"), ("Chevrolet", "Malibu", "Sedan"),
    ("Chevrolet", "Captiva", "SUV"), ("Chevrolet", "Tahoe", "SUV"),
    ("Chevrolet", "Aveo", "Sedan"), ("Chevrolet", "Equinox", "SUV"),
    ("Ravon", "Nexia R3", "Sedan"), ("Ravon", "R4", "Sedan"), ("Ravon", "Gentra", "Sedan"),
    ("Daewoo", "Nexia", "Sedan"), ("Daewoo", "Matiz", "Hatchback"), ("Daewoo", "Gentra", "Sedan"),
    # --- Renault / Peugeot / Citroen / Fiat / Dacia ---
    ("Renault", "Logan", "Sedan"), ("Renault", "Duster", "SUV"),
    ("Renault", "Sandero", "Hatchback"), ("Renault", "Megane", "Sedan"),
    ("Renault", "Fluence", "Sedan"), ("Renault", "Kaptur", "SUV"), ("Renault", "Arkana", "SUV"),
    ("Peugeot", "206", "Hatchback"), ("Peugeot", "301", "Sedan"),
    ("Peugeot", "308", "Hatchback"), ("Peugeot", "408", "Sedan"),
    ("Peugeot", "508", "Sedan"), ("Peugeot", "2008", "SUV"),
    ("Peugeot", "3008", "SUV"), ("Peugeot", "5008", "SUV"),
    ("Peugeot", "Partner", "Van"), ("Peugeot", "Boxer", "Van"),
    ("Citroen", "C3", "Hatchback"), ("Citroen", "C4", "Sedan"),
    ("Citroen", "C-Elysee", "Sedan"), ("Citroen", "Berlingo", "Van"),
    ("Fiat", "Doblo", "Van"), ("Fiat", "Egea", "Sedan"), ("Fiat", "500", "Hatchback"),
    ("Dacia", "Logan", "Sedan"), ("Dacia", "Duster", "SUV"), ("Dacia", "Sandero", "Hatchback"),
    # --- Chinese brands ---
    ("Chery", "Tiggo 4", "SUV"), ("Chery", "Tiggo 7", "SUV"), ("Chery", "Tiggo 8", "SUV"),
    ("Chery", "Arrizo 5", "Sedan"), ("Chery", "Bonus", "Sedan"),
    ("Haval", "H6", "SUV"), ("Haval", "Jolion", "SUV"), ("Haval", "F7", "SUV"),
    ("Geely", "Atlas", "SUV"), ("Geely", "Coolray", "SUV"), ("Geely", "Emgrand", "Sedan"),
    ("Lifan", "X60", "SUV"), ("Lifan", "Solano", "Sedan"), ("Lifan", "X50", "SUV"),
    # --- Premium / other ---
    ("Land Rover", "Defender", "SUV"), ("Land Rover", "Discovery", "SUV"),
    ("Land Rover", "Range Rover", "SUV"), ("Land Rover", "Range Rover Sport", "SUV"),
    ("Land Rover", "Range Rover Evoque", "SUV"), ("Land Rover", "Freelander", "SUV"),
    ("Porsche", "Cayenne", "SUV"), ("Porsche", "Macan", "SUV"),
    ("Porsche", "Panamera", "Sedan"), ("Porsche", "911", "Coupe"),
    ("Volvo", "S60", "Sedan"), ("Volvo", "S90", "Sedan"),
    ("Volvo", "XC40", "SUV"), ("Volvo", "XC60", "SUV"), ("Volvo", "XC90", "SUV"),
    ("Infiniti", "Q50", "Sedan"), ("Infiniti", "QX50", "SUV"),
    ("Infiniti", "QX60", "SUV"), ("Infiniti", "QX80", "SUV"), ("Infiniti", "FX", "SUV"),
    ("Jeep", "Grand Cherokee", "SUV"), ("Jeep", "Cherokee", "SUV"),
    ("Jeep", "Wrangler", "SUV"), ("Jeep", "Compass", "SUV"),
    ("Tesla", "Model 3", "Sedan"), ("Tesla", "Model Y", "SUV"),
    ("Tesla", "Model S", "Sedan"), ("Tesla", "Model X", "SUV"),
    # --- Iranian brands (common in region) ---
    ("Iran Khodro", "Samand", "Sedan"), ("Iran Khodro", "Dena", "Sedan"),
    ("Iran Khodro", "Runna", "Sedan"), ("Iran Khodro", "Peugeot 405", "Sedan"),
    ("Saipa", "Tiba", "Sedan"), ("Saipa", "Quick", "Hatchback"), ("Saipa", "Pride", "Sedan"),
    # --- ZAZ ---
    ("ZAZ", "Chance", "Sedan"), ("ZAZ", "Slavuta", "Hatchback"), ("ZAZ", "Tavria", "Hatchback"),
]
